# A minimal left prompt
#format = """${custom.system_icons}$username$hostname$directory$shlvl$character"""
format = """
╭─{ ${custom.system_icons}$username$hostname $directory$nix_shell} \
$git_branch$git_commit$git_state$git_metrics$git_status$python$ruby$rust$terraform
╰─$shlvl$character
"""
# move the rest of the prompt to the right
#right_format = """$all$status"""

add_newline = false

[fill]
symbol = " "

[username]
format = "[$user]($style)@"

[hostname]
format = "[$hostname]($style)"

[cmd_duration]
format = '\[[ $duration ]($style)\]'

[character]
success_symbol = "❯"
error_symbol = "❯"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " ro"
truncation_symbol = "…/"
truncation_length = 5
#home_symbol = "ﴤ"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[terraform]
format = "[$symbol$workspace]($style) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "
format = '[$symbol$state( \($name\))]($style) '

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
symbol = " "
format = "[$symbol($version )]($style)"

[rust]
symbol = " "
format = "[$symbol($version )]($style)"

[scala]
symbol = " "

[shlvl]
symbol = "❯"
format = "[$symbol]($style)"
repeat = false
disabled = false

[swift]
symbol = "ﯣ "

[custom.system_icons]
description = "Show system icons"
command     = '([ $(uname -s) == "Darwin" ] && echo ) || ([ $(uname -s) == "Linux" ] && echo )'
format      = "[$output]($style) "
style       = "bold"
shell       = ["bash", "--noprofile", "--norc"]
when        = "true"
