# - { ZStyle } ------------------------------------------------------------------------------ #
autoload -U compinit
zstyle ':completion:*' menu select

# - { Keybinds } ---------------------------------------------------------------------------- #
# Use ctrl+{arrows} to jump around words
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
